version: '3'
services:
  solr:
    image: solr:latest
    container_name: restaurant_geo
    ports:
      - "8983:8983"
    volumes:
      - ./data:/var/solr
    command:
      - solr-precreate
      - geotaste_restaurant

